### ISSUE TITLE
作者您好！想请教一下Yelp数据集中loadMat.py报错的问题

### ISSUE THREAD

**Issue by fujiaxu0207** [HKUDS/HGCL#16]
2024-06-12 20:52:24.284970
Traceback (most recent call last):
  File "loadMat.py", line 165, in <module>
    ratingMat,trustMat,categoryMat=filterData(ratingMat,trustMat,categoryMat)
  File "loadMat.py", line 74, in filterData
    trustMat=trustMat[idx][:,idx]
  File "/root/anaconda3/envs/xytf/fjx_HGCL/lib/python3.7/site-packages/scipy/sparse/_index.py", line 33, in __getitem__
    row, col = self._validate_indices(key)
  File "/root/anaconda3/envs/xytf/fjx_HGCL/lib/python3.7/site-packages/scipy/sparse/_index.py", line 138, in _validate_indices
    row = self._asindices(row, M)
  File "/root/anaconda3/envs/xytf/fjx_HGCL/lib/python3.7/site-packages/scipy/sparse/_index.py", line 170, in _asindices
    raise IndexError('index (%d) out of range' % max_indx)
IndexError: index (1968701) out of range

请问为什么越界了呢？使用的是dataraw里面的数据

**Comment by Mrzjk** [comment]
我看哪个loadMat文件中是为了节省内存，我把那一行注释也可以运行

**Comment by fujiaxu0207** [comment]
> 我看哪个loadMat文件中是为了节省内存，我把那一行注释也可以运行

应该是的

**Comment by cmr123456** [comment]
非常感谢您们的问题，之前yelp数据集上传的原始数据rawdata里的trust.csv是已经处理过的，由于误操作导致。然后因为内存大小的限制，我把yelp数据集的原始数据集rawdata已经放在/dataset目录下的README.md里展示的[Google Drive](https://drive.google.com/drive/folders/1ZvxETpLguIShLkcohxifaS5DXaEQoTNF?usp=drive_link)的地址。有什么问题，欢迎继续提问。

**Comment by FZYTina** [comment]
您好，[Google Drive]的地址需要访问权限，无法下载Yelp原始数据集，方便的话请提供新的地址，感谢！
